import type { Metadata } from "next";
import { Inter, Noto_Sans } from "next/font/google";
import "./globals.css"
import "../fonts/stylesheet.css"

const noto = Noto_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "COPD",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={noto.className}>{children}</body>
    </html>
  );
}
